# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`

In [3]:
#1. Import the numpy package under the name np (★☆☆)
#hint: import … as

import numpy as np

In [4]:
#2. Create a null vector of size 10 (★☆☆)
#hint: np.zeros

null_vec = np.zeros((1,10))  # Create an array of all zeros
print(null_vec)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [8]:
#3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#hint: array[4]

null_vec[0,4]=1
print(null_vec)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [10]:
#4. Create a vector with values ranging from 10 to 49 (★☆☆)
#hint: arange

range_vect = np.arange(10, 50)
print(range_vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
#5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#hint: reshape

matrix_1 = np.arange(0,9).reshape(3,3)
print(matrix_1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
#6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#hint: np.nonzero

vect_6 = np.array([1,2,0,0,4,0])

np.nonzero(vect_6 > 0)


(array([0, 1, 4]),)

In [26]:
#7. Create a 3x3 identity matrix (★☆☆)
#hint: np.eye

vect_7 = np.identity(3)
print (vect_7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
#8. Create a 3x3x3 array with random values (★☆☆)
#hint: np.random.random

np.random.seed(1000)
v_8 = np.random.random((3,3))
v_8

array([[0.65358959, 0.11500694, 0.95028286],
       [0.4821914 , 0.87247454, 0.21233268],
       [0.04070962, 0.39719446, 0.2331322 ]])